using System.Diagnostics;

namespace UncleTayHouse.Tests.Unit
{
    [TestClass]
    public sealed class GamePlayTests
    {
        [TestMethod]
        public void GamePlay_Tests()
        {
            string[,] commands = new string[,]
            {
                { "I", "[Inventory]" },
                { "SCORE", "Your score is 10 out of a possible 100." },
                { "JUMP", "You jump up and down a couple of times and feel more relaxed now, but nothing special happens." },
                { "TAKE", "Take what?" },
                { "DROP", "Drop what?" },
                { "DOOR", "Do what with DOOR?" },
                // 	{ 1 } FOYER (LOBBY) - The entryway to the house" },
                // 	There is a NEWSPAPER here" },
                { "take newspaper", "NEWSPAPER: taken" },
                { "look newspaper", "Tays house unlikely ever to be sold. tales of gutted stairwells and booby traps have spooked buyers..." },
                { "read newspaper", "Tays house unlikely ever to be sold. tales of gutted stairwells and booby traps have spooked buyers..." },
                { "w", "" },
                // 	{ 4 } HALLWAY - A narrow hallway which runs west of the foyer" },
                { "w", "" },
                // 	{ 5 } HALLWAY - A narrow hallway at the west end of the house, a door to north" },
                // 	There is a locked door to the north." },
                { "open door", "You don't have a key!" },
                // 	{ 5 } HALLWAY - A narrow hallway at the west end of the house, a door to north" },
                // 	There is a locked door to the north." },
                { "unlock door", "You don't have a key!" },
                // 	{ 5 } HALLWAY - A narrow hallway at the west end of the house, a door to north" },
                // 	There is a locked door to the north." },
                { "w", "" },
                // 	{ 10 } GARAGE - The cavernous garage holds a non-operational gremlin and piles of junk" },
                // 	There is a JACK here" },
                // 	There is a BUNGEE here" },
                { "look jack", "Tire jack for lifting heavy objects like cars" },
                // 	{ 10 } GARAGE - The cavernous garage holds a non-operational gremlin and piles of junk" },
                // 	There is a JACK here" },
                // 	There is a BUNGEE here" },
                { "look bungee", "Cord for bungee jumping" },
                // 	{ 10 } GARAGE - The cavernous garage holds a non-operational gremlin and piles of junk" },
                // 	There is a JACK here" },
                // 	There is a BUNGEE here" },
                { "take jack", "JACK: taken" },
                // 	{ 10 } GARAGE - The cavernous garage holds a non-operational gremlin and piles of junk" },
                // 	There is a BUNGEE here" },
                { "take bungee", "BUNGEE: taken" },
                // 	{ 10 } GARAGE - The cavernous garage holds a non-operational gremlin and piles of junk" },
                { "e", "" },
                // 	{ 5 } HALLWAY - A narrow hallway at the west end of the house, a door to north" },
                // 	There is a locked door to the north." },
                { "s", "" },
                // 	{ 9 } SMALL BEDROOM - This small bedroom has a twin bed and chair. It looks little used" },
                // 	There is a NOTE here" },
                { "read note", "The writing is reversed. Try to read it somewhere else..." },
                // 	{ 9 } SMALL BEDROOM - This small bedroom has a twin bed and chair. It looks little used" },
                // 	There is a NOTE here" },
                { "take note", "NOTE: taken" },
                // 	{ 9 } SMALL BEDROOM - This small bedroom has a twin bed and chair. It looks little used" },
                { "n", "" },
                // 	{ 5 } HALLWAY - A narrow hallway at the west end of the house, a door to north" },
                // 	There is a locked door to the north." },
                { "w", "" },
                // 	{ 10 } GARAGE - The cavernous garage holds a non-operational gremlin and piles of junk" },
                { "e", "" },
                // 	{ 5 } HALLWAY - A narrow hallway at the west end of the house, a door to north" },
                // 	There is a locked door to the north." },
                { "e", "" },
                // 	{ 4 } HALLWAY - A narrow hallway which runs west of the foyer" },
                { "n", "" },
                // 	{ 6 } DEN - This room has an ancient television" },
                // 	There is a COUCH here" },
                { "look couch", "An overstuffed, dusty couch" },
                // 	{ 6 } DEN - This room has an ancient television" },
                // 	There is a COUCH here" },
                { "move couch", "Your back is acting up, you will need some support" },
                // 	{ 6 } DEN - This room has an ancient television" },
                // 	There is a COUCH here" },
                { "move couch jack", "You can't fit the jack there, maybe try something else" },
                // 	{ 6 } DEN - This room has an ancient television" },
                // 	There is a COUCH here" },
                { "s", "" },
                // 	{ 4 } HALLWAY - A narrow hallway which runs west of the foyer" },
                { "s", "" },
                // 	{ 7 } BATHROOM - A dingy bathroom with a cracked sink" },
                // 	There is a CLOTHES here" },
                { "look clothes", "A disgusting pile of soiled laundry" },
                // 	{ 7 } BATHROOM - A dingy bathroom with a cracked sink" },
                // 	There is a CLOTHES here" },
                { "take clothes", "That seems pointless and unsanitary, they are too dirty!" },
                // 	{ 7 } BATHROOM - A dingy bathroom with a cracked sink" },
                // 	There is a CLOTHES here" },
                { "n", "" },
                // 	{ 4 } HALLWAY - A narrow hallway which runs west of the foyer" },
                { "e", "" },
                // 	{ 1 } FOYER (LOBBY) - The entryway to the house" },
                { "n", "" },
                // 	{ 2 } KITCHEN - Countertops are dusty and there are rusting pots and pans" },
                // 	Stairs lead down to a cellar. Several steps have collapsed, making the staircase unusable." },
                // 	There is a FRIDGE here" },
                // 	Something is barely visible under the fridge" },
                { "look fridge", "This old refrigerator's motor labors heavily" },
                // 	{ 2 } KITCHEN - Countertops are dusty and there are rusting pots and pans" },
                // 	Stairs lead down to a cellar. Several steps have collapsed, making the staircase unusable." },
                // 	There is a FRIDGE here" },
                // 	Something is barely visible under the fridge" },
                { "look under fridge", "This old refrigerator's motor labors heavily" },
                // 	{ 2 } KITCHEN - Countertops are dusty and there are rusting pots and pans" },
                // 	Stairs lead down to a cellar. Several steps have collapsed, making the staircase unusable." },
                // 	There is a FRIDGE here" },
                // 	Something is barely visible under the fridge" },
                { "use jack fridge", "I don't understand... (2w)" },
                // 	{ 2 } KITCHEN - Countertops are dusty and there are rusting pots and pans" },
                // 	Stairs lead down to a cellar. Several steps have collapsed, making the staircase unusable." },
                // 	There is a FRIDGE here" },
                // 	Something is barely visible under the fridge" },
                { "move fridge jack", "You jack up the fridge and find a fuse under it" },
                // 	{ 2 } KITCHEN - Countertops are dusty and there are rusting pots and pans" },
                // 	Stairs lead down to a cellar. Several steps have collapsed, making the staircase unusable." },
                // 	There is a FUSE here" },
                // 	There is a FRIDGE here" },
                { "look fuse", "Old-fashioned electrical fuse" },
                // 	{ 2 } KITCHEN - Countertops are dusty and there are rusting pots and pans" },
                // 	Stairs lead down to a cellar. Several steps have collapsed, making the staircase unusable." },
                // 	There is a FUSE here" },
                // 	There is a FRIDGE here" },
                { "take fuse", "FUSE: taken" },
                // 	{ 2 } KITCHEN - Countertops are dusty and there are rusting pots and pans" },
                // 	Stairs lead down to a cellar. Several steps have collapsed, making the staircase unusable." },
                // 	There is a FRIDGE here" },
                { "s", "" },
                // 	{ 1 } FOYER (LOBBY) - The entryway to the house" },
                { "e", "" },
                // 	{ 3 } SITTING ROOM - This room is two stories high and contains elegant chairs and couches" },
                // 	UP   : BALCONY" },
                // 	There is a picture high up on the wall" },
                { "look picture", "There is no PICTURE here" },
                // 	{ 3 } SITTING ROOM - This room is two stories high and contains elegant chairs and couches" },
                // 	UP   : BALCONY" },
                // 	There is a picture high up on the wall" },
                { "e", "" },
                // 	{ 11 } DINING ROOM - Trophies line the walls. there are six chairs around a long table" },
                { "w", "" },
                // 	{ 3 } SITTING ROOM - This room is two stories high and contains elegant chairs and couches" },
                // 	UP   : BALCONY" },
                // 	There is a picture high up on the wall" },
                { "u", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	Dark stairs lead up to the attic." },
                // 	There is a RAILING here" },
                { "jump", "You forgot your parachute. Or maybe something else..." },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	Dark stairs lead up to the attic." },
                // 	There is a RAILING here" },
                { "n", "" },
                // 	{ 13 } MASTER BEDROOM - This large corner bedroom has solid walnut furniture and a large mirror" },
                // 	There is a KEY here" },
                { "look key", "A small brass key" },
                // 	{ 13 } MASTER BEDROOM - This large corner bedroom has solid walnut furniture and a large mirror" },
                // 	There is a KEY here" },
                { "take key", "KEY: taken" },
                // 	{ 13 } MASTER BEDROOM - This large corner bedroom has solid walnut furniture and a large mirror" },
                { "s", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	Dark stairs lead up to the attic." },
                // 	There is a RAILING here" },
                { "look railing", "A railing or guardrail, is a system designed to keep people or objects from falling off the balcony." },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	Dark stairs lead up to the attic." },
                // 	There is a RAILING here" },
                { "tie bungee", "Tie to what?" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	Dark stairs lead up to the attic." },
                // 	There is a RAILING here" },
                { "tie bungee railing", "Bungee cord tied to Railing!" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	Dark stairs lead up to the attic." },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "jump", "You bungee off the balcony..." },
                // 	{ 30 } MID-AIR - Hanging from a bungee cord" },
                // 	There is a PICTURE here" },
                { "look picture", "Uncle tays in all his sallow glory" },
                //... and bunge cord spring back" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	Dark stairs lead up to the attic." },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "jump", "You bungee off the balcony..." },
                // 	{ 30 } MID-AIR - Hanging from a bungee cord" },
                // 	There is a PICTURE here" },
                { "take picture", "Taking the picture reveals a fusebox" },
                //... and bunge cord spring back" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	Dark stairs lead up to the attic." },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "jump", "You bungee off the balcony..." },
                // 	{ 30 } MID-AIR - Hanging from a bungee cord" },
                // 	There is a FUSEBOX here" },
                { "put fuse fusebox", "You put the fuse in the box. Power is restored in the Attic!" },
                //... and bunge cord spring back" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "u", "" },
                // 	{ 25 } ATTIC - A dusty attic with low sloping walls" },
                // 	There is a BRACE here" },
                // 	There is a MAGAZINE here" },
                { "look brace", "A back brace" },
                // 	{ 25 } ATTIC - A dusty attic with low sloping walls" },
                // 	There is a BRACE here" },
                // 	There is a MAGAZINE here" },
                { "take brace", "BRACE: taken" },
                // 	{ 25 } ATTIC - A dusty attic with low sloping walls" },
                // 	There is a MAGAZINE here" },
                { "look magazine", "Tays' strange inventions include booby-trapped doors and toys that open doors by remote control..." },
                // 	{ 25 } ATTIC - A dusty attic with low sloping walls" },
                // 	There is a MAGAZINE here" },
                { "take magazine", "MAGAZINE: taken" },
                // 	{ 25 } ATTIC - A dusty attic with low sloping walls" },
                { "d", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "e", "" },
                //You can't go that way" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "w", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "s", "" },
                // 	{ 15 } GAME ROOM - This elegant game room has a pool table and marble chessboard" },
                // 	There is a SPINNINGTOP here" },
                { "look spinningtop", "A child's toy (spinning top)" },
                // 	{ 15 } GAME ROOM - This elegant game room has a pool table and marble chessboard" },
                // 	There is a SPINNINGTOP here" },
                { "take spinningtop", "SPINNINGTOP: taken" },
                // 	{ 15 } GAME ROOM - This elegant game room has a pool table and marble chessboard" },
                { "w", "" },
                // 	{ 16 } CLOSET - A spacious closet off the gameroom" },
                // 	There is a GAINESBURGER here" },
                { "look gainesburger", "Supposedly dog food, though it appears to be made of plastic" },
                // 	{ 16 } CLOSET - A spacious closet off the gameroom" },
                // 	There is a GAINESBURGER here" },
                { "take gainesburger", "GAINESBURGER: taken" },
                // 	{ 16 } CLOSET - A spacious closet off the gameroom" },
                { "e", "" },
                // 	{ 15 } GAME ROOM - This elegant game room has a pool table and marble chessboard" },
                { "n", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "e", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "w", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "w", "" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is blocking a doorway to the north." },
                { "n", "" },
                //  You never did like that dog, and he will not let you pass" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is blocking a doorway to the north." },
                { "drop gainesburger", "The dog looks disgusted. maybe you should eat it" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is blocking a doorway to the north." },
                { "eat gainesburger", "There was a diamond hidden inside the gainesburger" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is blocking a doorway to the north." },
                // 	There is a DIAMOND here" },
                { "take diamond", "DIAMOND: taken" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is blocking a doorway to the north." },
                { "e", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "e", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "n", "" },
                // 	{ 13 } MASTER BEDROOM - This large corner bedroom has solid walnut furniture and a large mirror" },
                { "look mirror", "There is no MIRROR here" },
                // 	{ 13 } MASTER BEDROOM - This large corner bedroom has solid walnut furniture and a large mirror" },
                { "read note mirror", "Experiments on LEFT and RIGHT doors proceeding well; file for patent" },
                // 	{ 13 } MASTER BEDROOM - This large corner bedroom has solid walnut furniture and a large mirror" },
                { "s", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "w", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "w", "" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is blocking a doorway to the north." },
                { "e", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "e", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "i", " [Inventory] You are carrying:" },
                   //-NEWSPAPER" },
                   //-JACK" },
                   //-PICTURE" },
                   //-KEY" },
                   //-SPINNINGTOP" },
                   //-NOTE" },
                   //-BRACE" },
                   //-MAGAZINE" },
                   //-DIAMOND" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "d", "" },
                // 	{ 3 } SITTING ROOM - This room is two stories high and contains elegant chairs and couches" },
                // 	UP   : BALCONY" },
                // 	A bungee cord dangles from the railing above" },
                { "w", "" },
                // 	{ 1 } FOYER (LOBBY) - The entryway to the house" },
                { "w", "" },
                // 	{ 4 } HALLWAY - A narrow hallway which runs west of the foyer" },
                { "n", "" },
                // 	{ 6 } DEN - This room has an ancient television" },
                // 	There is a COUCH here" },
                { "move couch brace", "You move the couch and find a teddybear behind it" },
                // 	{ 6 } DEN - This room has an ancient television" },
                // 	There is a TEDDYBEAR here" },
                // 	There is a COUCH here" },
                { "take teddybear", "TEDDYBEAR: taken" },
                                // 	{ 6 } DEN - This room has an ancient television" },
                                // 	There is a COUCH here" },
                { "s", "" },
                // 	{ 4 } HALLWAY - A narrow hallway which runs west of the foyer" },
                { "i", " [Inventory] You are carrying:" },
                   //-NEWSPAPER" },
                   //-TEDDYBEAR" },
                   //-JACK" },
                   //-PICTURE" },
                   //-KEY" },
                   //-SPINNINGTOP" },
                   //-NOTE" },
                   //-BRACE" },
                   //-MAGAZINE" },
                   //-DIAMOND" },
                // 	{ 4 } HALLWAY - A narrow hallway which runs west of the foyer" },
                { "e", "" },
                // 	{ 1 } FOYER (LOBBY) - The entryway to the house" },
                { "e", "" },
                // 	{ 3 } SITTING ROOM - This room is two stories high and contains elegant chairs and couches" },
                // 	UP   : BALCONY" },
                // 	A bungee cord dangles from the railing above" },
                { "u", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "e", "" },
                //  You can't go that way" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "e", "" },
                //  You can't go that way" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "w", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "w", "" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is blocking a doorway to the north." },
                { "drop teddybear", "The dog chews his favorite toy and is soon asleep" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is snoring peacefully" },
                { "n", "" },
                // 	{ 18 } CHILD'S ROOM - Your cousin's room in happier times, before he ran off to join the baath party" },
                { "spin spinningtop", "There is a flash of light and a cracking sound! An opening appears in the east wall" },
                // 	{ 18 } CHILD'S ROOM - Your cousin's room in happier times, before he ran off to join the baath party" },
                { "e", "" },
                // 	{ 19 } SECRET ROOM - A dark chamber off the bedroom" },
                // 	There is a LOVERBOY here" },
                { "look loverboy", "Loverboy's first album in vinyl, worth an incalculable sum" },
                // 	{ 19 } SECRET ROOM - A dark chamber off the bedroom" },
                // 	There is a LOVERBOY here" },
                { "take loverboy", "LOVERBOY: taken" },
                // 	{ 19 } SECRET ROOM - A dark chamber off the bedroom" },
                { "w", "" },
                // 	{ 18 } CHILD'S ROOM - Your cousin's room in happier times, before he ran off to join the baath party" },
                { "s", "" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is snoring peacefully" },
                { "w", "" },
                //  You can't go that way" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	A locked door to the WEST is labelled 'EXTREME DANGER'." },
                // 	Your uncle's doberman is snoring peacefully" },
                { "open door", "You unlock the door. Beware!" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	Your uncle's doberman is snoring peacefully" },
                { "w", "" },
                // 	{ 20 } DANGEROUS HALL - This eerie hall has three identical doors on the west wall (left, center, right)" },
                { "open center door", "Opening the door reveals a dumbwaiter in the west room" },
                // 	{ 20 } DANGEROUS HALL - This eerie hall has three identical doors on the west wall (left, center, right)" },
                { "w", "" },
                // 	{ 23 } DUMBWAITER - A jammed dumbwaiter (second floor)" },
                { "look dumbwaiter", "There is no DUMBWAITER here" },
                // 	{ 23 } DUMBWAITER - A jammed dumbwaiter (second floor)" },
                { "open dumbwaiter", "Open what?" },
                // 	{ 23 } DUMBWAITER - A jammed dumbwaiter (second floor)" },
                { "e", "" },
                // 	{ 20 } DANGEROUS HALL - This eerie hall has three identical doors on the west wall (left, center, right)" },
                { "s", "" },
                // 	{ 22 } BATHROOM - An elegant bath with a mirror over a marble sink" },
                // 	There is a GLOVES here" },
                // 	There is a MIRROR here" },
                { "take gloves", "GLOVES: taken" },
                // 	{ 22 } BATHROOM - An elegant bath with a mirror over a marble sink" },
                // 	There is a MIRROR here" },
                { "look gloves", "Rubber gloves used for cleaning" },
                // 	{ 22 } BATHROOM - An elegant bath with a mirror over a marble sink" },
                // 	There is a MIRROR here" },
                { "look mirror", "A mirror in the wall" },
                // 	{ 22 } BATHROOM - An elegant bath with a mirror over a marble sink" },
                // 	There is a MIRROR here" },
                { "take mirror", "MIRROR: taken" },
                // 	{ 22 } BATHROOM - An elegant bath with a mirror over a marble sink" },
                { "n", "" },
                // 	{ 20 } DANGEROUS HALL - This eerie hall has three identical doors on the west wall (left, center, right)" },
                { "e", "" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	Your uncle's doberman is snoring peacefully" },
                { "e", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "e", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "d", "" },
                // 	{ 3 } SITTING ROOM - This room is two stories high and contains elegant chairs and couches" },
                // 	UP   : BALCONY" },
                // 	A bungee cord dangles from the railing above" },
                { "w", "" },
                // 	{ 1 } FOYER (LOBBY) - The entryway to the house" },
                { "w", "" },
                // 	{ 4 } HALLWAY - A narrow hallway which runs west of the foyer" },
                { "s", "" },
                // 	{ 7 } BATHROOM - A dingy bathroom with a cracked sink" },
                // 	There is a CLOTHES here" },
                { "move clothes gloves", "Moving the clothes reveals a laundry chute to the basement" },
                // 	{ 7 } BATHROOM - A dingy bathroom with a cracked sink" },
                // 	DOWN         : LAUNDRY" },
                // 	There is a CLOTHES here" },
                { "d", "" },
                // 	{ 27 } LAUNDRY - This room has a washer and dryer, as well as a boiler and furnace" },
                // 	There is a LOONS here" },
                { "w", "" },
                // 	{ 26 } STORAGE ROOM - A bare room used to store random equipment and furniture" },
                // 	There is a BOXSPRING here" },
                { "look boxspring", "A queen-sized boxspring" },
                // 	{ 26 } STORAGE ROOM - A bare room used to store random equipment and furniture" },
                // 	There is a BOXSPRING here" },
                { "take boxspring", "BOXSPRING: taken" },
                // 	{ 26 } STORAGE ROOM - A bare room used to store random equipment and furniture" },
                { "e", "" },
                // 	{ 27 } LAUNDRY - This room has a washer and dryer, as well as a boiler and furnace" },
                // 	There is a LOONS here" },
                { "e", "" },
                // 	{ 28 } WORK ROOM - Equipment for working wood and metal" },
                // 	There is a OILCAN here" },
                { "w", "" },
                // 	{ 27 } LAUNDRY - This room has a washer and dryer, as well as a boiler and furnace" },
                // 	There is a LOONS here" },
                { "look loons", "A thick wad of canadian notes" },
                // 	{ 27 } LAUNDRY - This room has a washer and dryer, as well as a boiler and furnace" },
                // 	There is a LOONS here" },
                { "take loons", "LOONS: taken" },
                // 	{ 27 } LAUNDRY - This room has a washer and dryer, as well as a boiler and furnace" },
                { "e", "" },
                // 	{ 28 } WORK ROOM - Equipment for working wood and metal" },
                // 	There is a OILCAN here" },
                { "look oilcan", "This can contains fine lubricating oil" },
                // 	{ 28 } WORK ROOM - Equipment for working wood and metal" },
                // 	There is a OILCAN here" },
                { "take oilcan", "OILCAN: taken" },
                // 	{ 28 } WORK ROOM - Equipment for working wood and metal" },
                { "e", "" },
                // 	{ 29 } BOTTOM OF STAIRS - Stairs from basement to kitchen" },
                // 	Stairs lead up. Several steps have collapsed, making the staircase unusable." },
                { "drop boxspring", "The boxspring covers the gap in the stairs" },
                // 	{ 29 } BOTTOM OF STAIRS - Stairs from basement to kitchen" },
                // 	UP   : KITCHEN" },
                { "u", "" },
                // 	{ 2 } KITCHEN - Countertops are dusty and there are rusting pots and pans" },
                // 	DOWN         : BOTTOM OF STAIRS" },
                // 	There is a FRIDGE here" },
                // 	Something is barely visible under the fridge" },
                { "s", "" },
                // 	{ 1 } FOYER (LOBBY) - The entryway to the house" },
                { "e", "" },
                // 	{ 3 } SITTING ROOM - This room is two stories high and contains elegant chairs and couches" },
                // 	UP   : BALCONY" },
                // 	A bungee cord dangles from the railing above" },
                { "u", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "w", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "w", "" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	Your uncle's doberman is snoring peacefully" },
                { "w", "" },
                // 	{ 20 } DANGEROUS HALL - This eerie hall has three identical doors on the west wall (left, center, right)" },
                { "w", "" },
                // 	{ 23 } DUMBWAITER - A jammed dumbwaiter (second floor)" },
                { "oil dumbwaiter", "I don't understand... (2w)" },
                // 	{ 23 } DUMBWAITER - A jammed dumbwaiter (second floor)" },
                { "oil dumbwaiter oilcan", "The dumbwaiter mechanism now runs smoothly" },
                // 	{ 23 } DUMBWAITER - A jammed dumbwaiter (second floor)" },
                // 	DOWN         : DUMBWAITER" },
                { "d", "" },
                // 	{ 24 } DUMBWAITER - A dumbwaiter (main floor)" },
                // 	UP   : DUMBWAITER" },
                { "e", "" },
                // 	{ 8 } LIBRARY - This well-furnished library is lined with books and leather furniture" },
                // 	There is a locked door to the south." },
                // 	There is a CHECKBOOK here" },
                { "look checkbook", "Uncle tays' checkbook lists a balance of $220,000" },
                // 	{ 8 } LIBRARY - This well-furnished library is lined with books and leather furniture" },
                // 	There is a locked door to the south." },
                // 	There is a CHECKBOOK here" },
                { "take checkbook", "CHECKBOOK: taken" },
                // 	{ 8 } LIBRARY - This well-furnished library is lined with books and leather furniture" },
                // 	There is a locked door to the south." },
                { "open door", "Nothing to unlock!" },
                // 	{ 8 } LIBRARY - This well-furnished library is lined with books and leather furniture" },
                // 	There is a locked door to the south." },
                { "score", "Your score is 60 out of a possible 100." },
                // 	{ 8 } LIBRARY - This well-furnished library is lined with books and leather furniture" },
                // 	There is a locked door to the south." },
                { "w", "" },
                // 	{ 24 } DUMBWAITER - A dumbwaiter (main floor)" },
                // 	UP   : DUMBWAITER" },
                { "u", "" },
                // 	{ 23 } DUMBWAITER - A jammed dumbwaiter (second floor)" },
                // 	DOWN         : DUMBWAITER" },
                { "e", "" },
                // 	{ 20 } DANGEROUS HALL - This eerie hall has three identical doors on the west wall (left, center, right)" },
                { "n", "" },
                // 	{ 21 } CORNER BEDROOM - A cozy corner room with windows on two walls" },
                // 	There is a INVESTMENT here" },
                { "look investment", "Pre-ipo shares of apollo computing have to be worth ... something" },
                // 	{ 21 } CORNER BEDROOM - A cozy corner room with windows on two walls" },
                // 	There is a INVESTMENT here" },
                { "take investment", "INVESTMENT: taken" },
                // 	{ 21 } CORNER BEDROOM - A cozy corner room with windows on two walls" },
                { "score", "Your score is 70 out of a possible 100." },
                // 	{ 21 } CORNER BEDROOM - A cozy corner room with windows on two walls" },
                // 	{ 21 } CORNER BEDROOM - A cozy corner room with windows on two walls" },
                { "s", "" },
                // 	{ 20 } DANGEROUS HALL - This eerie hall has three identical doors on the west wall (left, center, right)" },
                { "e", "" },
                // 	{ 17 } HALLWAY - A hallway in the center of the second floor" },
                // 	Your uncle's doberman is snoring peacefully" },
                { "e", "" },
                // 	{ 14 } HALLWAY - A hallway with a large arch on its south side" },
                { "e", "" },
                // 	{ 12 } BALCONY - Balcony above the sitting room. a railing protects you from a 15-foot drop" },
                // 	A bungee cord dangles from the railing" },
                // 	There is a RAILING here" },
                { "d", "" },
                // 	{ 3 } SITTING ROOM - This room is two stories high and contains elegant chairs and couches" },
                // 	UP   : BALCONY" },
                // 	A bungee cord dangles from the railing above" },
                { "w", "" },
                // 	{ 1 } FOYER (LOBBY) - The entryway to the house" },

            };

            Game game = new();
            // set center (2) door fixed for testing
            game.gameState.SafeDoor = 2;

            // start at the FOYER
            Assert.IsTrue(game.gameState.IsPlayerAt(CteRooms.FOYER1));

            for (int i = 0; i < commands.GetLength(0); i++)
            {
                string prompt = commands[i, 0];
                string response = commands[i, 1];

                game.ActionPrep();
                game.userInput = GameUserInput.ProcessInput(prompt);
                game.ActionProcessInput();

                // MOVE does not produce response, so skip it
                if (string.IsNullOrEmpty(response))
                {
                    continue;
                }

                // show responses
                var msgList = String.Join(" => ", game.gameState.Msg);
                var msgDebug = $"P: {prompt}  R: {response} M: {msgList}";
                Debug.WriteLine(msgDebug);

                bool exists = game.gameState.Msg.Any(m => m.Contains(response));
                Assert.IsTrue(game.gameState.Msg.Any());
                Assert.IsTrue(exists, "Expected " + response);

                game.gameState.Msg.Clear();
            }
        }
    }
}
