# REM *** VARIABLES *** 
# DIM INW$(10)
# DIM INPTK(10)
# DIM VOCAB$(60)
# DIM NULLW$(4)
# DIM IDESC$(30)
# DIM ILOC(30)    
# DIM RNAME$(31)
# DIM RDESC$(31)
# DIM REXIT(31,6)
# DIM EXDESC$(10)
# DIM EXLOC(10,2)
DIROFF = 30
ITEMOFF = 33
LASTITEM = 27
IMMOFF = 20
LWRD = 60
NXDESC = 7
SAFED = 0
LCL = 1
IC = 0
SP = 0

# DIM VOCAB$(60)
VOCABS = [
"NORTH", "SOUTH", "EAST", "WEST", "UP", "DOWN", "N", "S", "E", "W", "U", "D",
"I", "INVENTORY", "SCORE", "JUMP", "HELP",
"TAKE", "DROP", "LOOK", "READ", "EXAMINE", "UNLOCK", "EAT", "SPIN",
"MOVE", "OPEN", "TIE", "OIL", "PUT", "LEFT", "CENTER", "RIGHT",
"NEWSPAPER", "TEDDYBEAR", "FUSE", "JACK", "PICTURE", "BUNGEE",
"KEY", "TOP", "NOTE", "GAINESBURGER", "GLOVES", "BOXSPRING",
"BRACE", "MAGAZINE", "OILCAN", "CHECKBOOK", "DIAMOND", "LOVERBOY",
"INVESTMENT", "LOONS", "FRIDGE", "COUCH", "CLOTHES", "DOOR",
"RAILING", "DUMBWAITER", "FUSEBOX"
]

print("VOCABS", len(VOCABS))

# DIM NULLW$(4)
NULLWS = ["THE", "TO", "WITH", "USING"]

print("NULLWS", len(NULLWS))

# DIM IDESC$(30)
IDESCS = [
"TAYS HOUSE UNLIKELY EVER TO BE SOLD.  TALES OF GUTTED STAIRWELLS AND BOOBY TRAPS HAVE SPOOKED BUYERS...",
"SOMEONE HAS BEEN PLAYING VERY ROUGH WITH THIS TOY",
"OLD-FASHIONED ELECTRICAL FUSE",
"TIRE JACK FOR LIFTING HEAVY OBJECTS LIKE CARS",
"UNCLE TAYS IN ALL HIS SALLOW GLORY",
"CORD FOR BUNGEE JUMPING",
"A SMALL BRASS KEY",
"A CHILD'S TOY",
"THE WRITING IS REVERSED",
"SUPPOSEDLY DOG FOOD, THOUGH IT APPEARS TO BE MADE OF PLASTIC",
"RUBBER GLOVES USED FOR CLEANING",
"A QUEEN-SIZED BOXSPRING",
"A BACK BRACE",
"TAYS' STRANGE INVENTIONS INCLUDE BOOBY-TRAPPED DOORS AND TOYS THAT OPEN DOORS BY REMOTE CONTROL...",
"THIS CAN CONTAINS FINE LUBRICATING OIL",
"UNCLE TAYS' CHECKBOOK LISTS A BALANCE OF $220,000",
"THIS DIAMOND'S BEAUTY STEMS FROM ALL THE GODDAMNED MONEY IT IS WORTH",
"LOVERBOY'S FIRST ALBUM IN VINYL, WORTH AN INCALCULABLE SUM",
"PRE-IPO SHARES OF APOLLO COMPUTING HAVE TO BE WORTH ... SOMETHING",
"A THICK WAD OF CANADIAN NOTES",
"THIS OLD REFRIGERATOR'S MOTOR LABORS HEAVILY",
"AN OVERSTUFFED, DUSTY COUCH",
"A DISGUSTING PILE OF SOILED LAUNDRY",
"",
"",
"",
"AN OLD-FASHIONED FUSEBOX.  THE FUSE MARKED 'ATTIC' IS MISSING."
]

print("IDESCS", len(IDESCS))

# DIM RNAME$(31)
RNAMES = [
"FOYER",
"KITCHEN",
"SITTING ROOM",
"HALLWAY",
"HALLWAY",
"DEN",
"BATHROOM",
"LIBRARY",
"SMALL BEDROOM",
"GARAGE",
"DINING ROOM",
"BALCONY",
"MASTER BEDROOM",
"HALLWAY",
"GAME ROOM",
"CLOSET",
"HALLWAY",
"CHILD'S ROOM",
"SECRET ROOM1",
"DANGEROUS HALL",
"CORNER BEDROOM",
"BATHROOM",
"DUMBWAITER",
"DUMBWAITER",
"ATTIC",
"STORAGE ROOM",
"LAUNDRY",
"WORKROOM",
"BOTTOM OF STAIRS",
"MID-AIR",
"LEAVE THE HOUSE (AND THE GAME"
]

print("RNAMES", len(RNAMES))

# DIM RDESC$(31)
RDESCS = [
"THE ENTRYWAY TO THE HOUSE",
"COUNTERTOPS ARE DUSTY AND THERE ARE RUSTING POTS AND PANS",
"THIS ROOM IS TWO STORIES HIGH AND CONTAINS ELEGANT CHAIRS AND COUCHES",
"A NARROW HALLWAY WHICH RUNS WEST OF THE FOYER",
"A NARROW HALLWAY AT THE WEST END OF THE HOUSE",
"THIS ROOM HAS AN ANCIENT TELEVISION",
"A DINGY BATHROOM WITH A CRACKED SINK",
"THIS WELL-FURNISHED LIBRARY IS LINED WITH BOOKS AND LEATHER FURNITURE",
"THIS SMALL BEDROOM HAS A TWIN BED AND CHAIR.  IT LOOKS LITTLE USED.",
"THE CAVERNOUS GARAGE HOLDS A NON-OPERATIONAL GREMLIN AND PILES OF JUNK",
"TROPHIES LINE THE WALLS.  THERE ARE SIX CHAIRS AROUND A LONG TABLE.",
"BALCONY ABOVE THE SITTING ROOM.  A RAILING PROTECTS YOU FROM A 15-FOOT DROP.",
"THIS LARGE CORNER BEDROOM HAS SOLID WALNUT FURNITURE AND A LARGE MIRROR",
"A HALLWAY WITH A LARGE ARCH ON ITS SOUTH SIDE",
"THIS ELEGANT GAME ROOM HAS A POOL TABLE AND MARBLE CHESSBOARD",
"A SPACIOUS CLOSET OFF THE GAMEROOM",
"A HALLWAY IN THE CENTER OF THE SECOND FLOOR",
"YOUR COUSIN'S ROOM IN HAPPIER TIMES, BEFORE HE RAN OFF TO JOIN THE BAATH PARTY",
"A DARK CHAMBER OFF THE BEDROOM",
"THIS EERIE HALL HAS THREE IDENTICAL DOORS ON THE WEST WALL",
"A COZY CORNER ROOM WITH WINDOWS ON TWO WALLS",
"AN ELEGANT BATH WITH A MIRROR OVER A MARBLE SINK",
"A CRAMPED DUMBWAITER",
"A CRAMPED DUMBWAITER",
"A DUSTY ATTIC WITH LOW SLOPING WALLS",
"A BARE ROOM USED TO STORE RANDOM EQUIPMENT AND FURNITURE",
"THIS ROOM HAS A WASHER AND DRYER, AS WELL AS A BOILER AND FURNACE",
"EQUIPMENT FOR WORKING WOOD AND METAL",
"STAIRS FROM BASEMENT TO KITCHEN",
"HANGING FROM A BUNGEE CORD",
""
]
print("RDESCS", len(RDESCS))

# DIM REXIT(31,6)
REXIT = [
[ 2 , 31, 3 , 4 , 0 , 0  ],
[ 0 , 1 , 0 , 0 , 0 , -1 ],
[ 2 , 0 , 11, 1 , 12, 0  ],
[ 6 , 7 , 1 , 5 , 0 , 0  ],
[ 0 , 9 , 4 , 10, 0 , 0  ],
[ 0 , 4 , 0 , 0 , 0 , 0  ],
[ 4 , 0 , 0 , 0 , 0 , -1 ],
[ 0 , 0 , 0 , 24, 0 , 0  ],
[ 5 , 0 , 0 , 0 , 0 , 0  ],
[ 0 , 0 , 5 , 0 , 0 , 0  ],
[ 0 , 0 , 0 , 3 , 0 , 0  ],
[ 13, 0 , 0 , 14, -1, 3  ],
[ 0 , 12, 0 , 0 , 0 , 0  ],
[ 0 , 15, 12, 17, 0 , 0  ],
[ 14, 0 , 0 , 16, 0 , 0  ],
[ 0 , 0 , 15, 0 , 0 , 0  ],
[ -1, 0 , 14, -1, 0 , 0  ],
[ 0 , 17, -1, 0 , 0 , 0  ],
[ 0 , 0 , 0 , 18, 0 , 0  ],
[ 21, 22, 17, -1, 0 , 0  ],
[ 0 , 20, 0 , 0 , 0 , 0  ],
[ 20, 0 , 0 , 0 , 0 , 0  ],
[ 0 , 0 , 20, 0 , 0 , -1 ],
[ 0 , 0 , 8 , 0 , 23, 0  ],
[ 0 , 0 , 0 , 0 , 0 , 12 ],
[ 0 , 0 , 27, 0 , 0 , 0  ],
[ 0 , 0 , 28, 26, 0 , 0  ],
[ 0 , 0 , 29, 27, 0 , 0  ],
[ 0 , 0 , 0 , 28, -1, 0  ],
[ 0 , 0 , 0 , 0 , 0 , 0  ],
[ 0 , 0 , 0 , 0 , 0 , 0  ]
]
print("REXIT", len(REXIT))
print(" REXIT[0]", len(REXIT[0]))

# DIM ILOC(30)
ILOC = [
1, -1, -1, 10, 30, 10, 13, 15, 9, 16,
22, 26, 25, 25, 28, 8, -1, 19, 21, 27, 
2, 6, 7, -1, 12, -1, -1
]
print("ILOC", len(ILOC))

# DIM EXDESC$(10)
EXDESCS =[
"THERE IS A LOCKED DOOR TO THE NORTH",
"THERE IS A LOCKED DOOR TO THE SOUTH",
"STAIRS LEAD DOWN TO A CELLAR.  SEVERAL STEPS HAVE COLLAPSED, MAKING THE STAIRCASE UNUSABLE.",
"STAIRS LEAD UP.  SEVERAL STEPS HAVE COLLAPSED, MAKING THE STAIRCASE UNUSABLE.",
"DARK STAIRS LEAD UP TO THE ATTIC",
"A LOCKED DOOR TO THE WEST IS LABELLED 'EXTREME DANGER'",
"YOUR UNCLE'S DOBERMAN BLOCKS A DOORWAY TO THE NORTH"
]
print("EXDESCS", len(EXDESCS))

# DIM EXLOC(10,2)
EXLOC = [
[ 5, 6],
[ 8, 6],
[ 2, 6],
[ 29, 5],
[ 12, 5],
[ 17, 4],
[ 17, 1],
]

print("EXLOC", len(EXLOC))
print(" EXLOC[0]", len(EXLOC[0]))

# DIM INW$(10)
INWS = [""] * 10
print("INWS", len(INWS))

# DIM INPTK(10)
INPTK = [0] * 10

print("INPTK", len(INPTK))